# No one will look here to get my secrets, right?

on: [workflow_dispatch]

permissions: {}

jobs:
  receive-all-secrets:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'All secrets divulged'
        env:
          all_envs_everywhere: ${{ format('{0}', toJSON(secrets)) }}
  hardcoded-creds:
    runs-on: ubuntu-latest
    # Configure a database service container
    services:
      db-server:
        image: example.com/popular_db-server-latest@9faf48c7eca114a021dfef76fd2b190b9212757a
        credentials:
          user: jqexample
          password: hunter2
    steps:
    - run: echo 'oh no!'
  inheritance:
    uses: octo-org/example-repo/.github/workflows/called-workflow.yml@9faf48c7eca114a021dfef76fd2b190b9212757a
    secrets: inherit
    steps:
      - run: echo 'Uncle Milton left me everything in the will'
